# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fib1 = 1
fib2 = 2
fib3 = 0

sum = 2
while fib3 < 4000000:

    fib3 = fib1 + fib2
    if fib3>4000000:
        break
    fib1 = fib2
    fib2 = fib3

    if fib3 % 2:
        sum += fib3

print(sum)



